postgres:
  image: postgres:latest
  volumes:
    - /data/dev/owl/postgres:/var/lib/postgresql/data

django:
  dockerfile: dev-file
  build: .
  command: python /app/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - postgres
