postgres:
  image: postgres:latest
  volumes:
    - /data/owl/postgres:/var/lib/postgresql/data
  env_file: .env
  ports:
    - "5432:5432"

django:
  build: .
  dockerfile: ./compose/prod-file
  restart: always
  user: django
  links:
    - postgres
    - redis
  command: /gunicorn.sh
  env_file: .env

nginx:
  build: ./compose/nginx
  links:
    - django:django
  ports:
    - "0.0.0.0:80:80"
  volumes:
    - /www/static
  volumes_from:
    - django

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"
