# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20160213_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warpapplication',
            name='category',
            field=models.CharField(choices=[('WEB', 'WEB'), ('MOBILE', 'MOBILE')], default='WEB', max_length=10, verbose_name='Category'),
        ),
    ]
