# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformapp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials_platformapp', to=settings.AUTH_USER_MODEL),
        ),
    ]
