# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypage',
            name='show_header',
            field=models.BooleanField(default=False, help_text='Show header image in main list', verbose_name='Show'),
        ),
    ]
