# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 00:16
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161015_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('python', 'Python'), ('javascript', 'Javascript'), ('json', 'JSON'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS'), ('yaml', 'YAML')])), ('code', wagtail.wagtailcore.blocks.TextBlock(help_text='Código')), ('theme', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('autumn', 'Autumn'), ('borland', 'Borland'), ('bw', 'BW'), ('colorful', 'Colorful'), ('default', 'Default'), ('emacs', 'Emacs'), ('friendly', 'Friendly'), ('fruity', 'Fruity'), ('github', 'Github'), ('manni', 'Manni'), ('monokai', 'Monokai'), ('murphy', 'Murphy'), ('native', 'Native'), ('pastie', 'pastie'), ('perldoc', 'PerlDoc'), ('tango', 'Tango'), ('trac', 'Trac'), ('vim', 'Vim'), ('vs', 'VS'), ('zenburn', 'Zenburn')], default='monokai', help_text='Estilo'))))))),
        ),
    ]
