# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('blog', '0002_entrypage_show_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Project name')),
                ('link', models.URLField(unique=True)),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_projects', to='blog.BlogPage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.Project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, unique=True, verbose_name='Speech title')),
                ('Comunity', models.CharField(max_length=140, unique=True, verbose_name='Destiny')),
                ('link', models.URLField(unique=True, verbose_name='Link to slides')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image')),
            ],
            options={
                'verbose_name': 'Speech',
                'verbose_name_plural': 'Speeches',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SpeechBlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_speeches', to='blog.BlogPage')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.Speech', verbose_name='Speech')),
            ],
        ),
        migrations.AlterField(
            model_name='entrypage',
            name='show_header',
            field=models.BooleanField(default=False, help_text='Show header image in main list', verbose_name='Show header'),
        ),
    ]
