# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160720_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech',
            old_name='Comunity',
            new_name='community',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Full visualization image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ForeignKey(blank=True, help_text='Small image to previsualization 350 x 350', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
    ]
