# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 06:19
from __future__ import unicode_literals

import blog.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161025_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', label='Titulo', template='blog/blocks/heading.html')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(label='Párrafo')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Imagen', template='blog/blocks/image.html')), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('python', 'Python'), ('javascript', 'Javascript'), ('json', 'JSON'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS'), ('yaml', 'YAML')], default='python', label='Lenguaje')), ('code', wagtail.wagtailcore.blocks.TextBlock(classname='full', help_text='Código', label='Código')), ('theme', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('autumn', 'Autumn'), ('borland', 'Borland'), ('bw', 'BW'), ('colorful', 'Colorful'), ('default', 'Default'), ('emacs', 'Emacs'), ('friendly', 'Friendly'), ('fruity', 'Fruity'), ('github', 'Github'), ('manni', 'Manni'), ('monokai', 'Monokai'), ('murphy', 'Murphy'), ('native', 'Native'), ('pastie', 'pastie'), ('perldoc', 'PerlDoc'), ('tango', 'Tango'), ('trac', 'Trac'), ('vim', 'Vim'), ('vs', 'VS'), ('zenburn', 'Zenburn')], default='monokai', label='Estilo'))), label='Código')), ('markdown', blog.blocks.MarkDownBlock(label='Markdown')), ('rst', blog.blocks.RSTBlock(label='RST')))),
        ),
    ]
