# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('blog', '0004_auto_20160720_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Full visualization image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ForeignKey(blank=True, help_text='Small image to previsualization 350 x 350', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Thumb'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='community',
            field=models.CharField(max_length=140, unique=True, verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Thumb'),
        ),
    ]
