# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('blog', '0005_auto_20160721_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypage',
            name='author_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='author_phrase',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='phrase'),
        ),
    ]
